// Cart Actions
export const LOAD_CART_ITEMS = 'LOAD_CART_ITEMS'
export const ADD_CART_ITEMS = 'ADD_CART_ITEMS'
export const REMOVE_CART_ITEMS = 'REMOVE_CART_ITEMS'
// Products Actions (async)
export const  FETCH_PRODUCTS_SUCESS = 'FETCH_PRODUCTS_SUCESS'
export const  FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'
export const  FETCH_PRODUCT_SUCESS = 'FETCH_PRODUCT_SUCESS'
export const  FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE'
export const  SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS'
export const  SAVE_PRODUCT_FAILURE = 'SAVE_PRODUCT_FAILURE'
